### PR TITLE
Add and use `indexed_type` field

### PR DESCRIPTION
**Pull request by 0xmaayan**
### Description

Add new `indexed_type` field for `events` query

https://aptos-org.slack.com/archives/C03MN5F7WUV/p1697815925868219

### Test Plan
`getAccountEventsByEventType` test is failing because localnet needs to be regenerate with the new field, @banool is working on it
https://aptos-org.slack.com/archives/C03MN5F7WUV/p1699286279415299?thread_ts=1697815925.868219&cid=C03MN5F7WUV

### CODE REVIEW

**Review by 0xjinn — APPROVED** [review]
Looking at the table from hasura, is this the index id generated by "event type"? In this case, the user has to know what `id` the event they are querying for?

**Comment by 0xmaayan** [comment]
> Looking at the table from hasura, is this the index id generated by "event type"? In this case, the user has to know what `id` the event they are querying for?

no, this is the indexed event type

**Review by gregnazario — APPROVED** [review]

**Comment by gregnazario** [comment]
Looks like the local testnet doesn't have this field, it needs to be updated in a CLI release?

**Comment by 0xmaayan** [comment]
> ### Test Plan
> `getAccountEventsByEventType` test is failing because localnet needs to be regenerate with the new field, @banool is working on it https://aptos-org.slack.com/archives/C03MN5F7WUV/p1699286279415299?thread_ts=1697815925.868219&cid=C03MN5F7WUV

yes
```
Test Plan
getAccountEventsByEventType test is failing because localnet needs to be regenerate with the new field, @banool is working on it
https://aptos-org.slack.com/archives/C03MN5F7WUV/p1699286279415299?thread_ts=1697815925.868219&cid=C03MN5F7WUV
```

**Pull request merged**
