### PR TITLE
Add randomnet to known networks

### PR DESCRIPTION
**Pull request by 0xaptosj**

### CODE REVIEW

**Review by 0xmaayan — COMMENTED** [review]
LGTM. Could we update CHANGELOG with this change? also, is there a fixed chain_id for randomnet?

**Comment by 0xaptosj** [comment]
> LGTM. Could we update CHANGELOG with this change? also, is there a fixed chain_id for randomnet?

both addressed

**Review by 0xmaayan — APPROVED** [review]

**Comment by 0xmaayan** [comment]
sorry, could we also add tests?

**Comment by 0xaptosj** [comment]
> sorry, could we also add tests? https://github.com/aptos-labs/aptos-ts-sdk/blob/main/tests/unit/aptosConfig.test.ts#L15

Added

**Pull request merged**
